config/routes.rb
TextVisualizer::Application.routes.draw do
  resources :text_maps
  root :to => "text_maps#index" 
end

app/models/my_html_renderer.rb
class MyHTMLRenderer < Redcarpet::Render::HTML
  def header(text, header_level, options)


    if header_level == 1 
        if @h1_is_open == nil
          @h1_is_open = true
          s = "<div class='h1bracket'><div class='h1item h1box'><h#{header_level}>#{text}</h#{header_level}></div>"
          return s
        end

        s = "</div></div>\n<div class='h1bracket'><div class='h1item h1box'><h#{header_level}>#{text}</h#{header_level}>"
        return s

      end

      if header_level == 2
        if @h2_is_open == nil
          @h2_is_open = true  
          s = "<div class='h2bracket'><div class='h2item h2box'><h#{header_level}>#{text}</h#{header_level}></div>"
          return s
        end

          s = "</div>\n<div class='h2bracket'><div class='h2item h2box'><h#{header_level}>#{text}</h#{header_level}></div>"
          return s
      end
      if header_level == 3
        s = "<div class='h3bracket'><div class='h3item h3box'><h#{header_level}>#{text}</h#{header_level}></div></div>"
        return s
      end


      if header_level == 4
        s = "<div class='box column2'><h#{header_level}>#{text}</h#{header_level}></div>"
        return s
      end

      # def open_brackets
      #   if nil
      #     {1 => 0, 2 => 0, 3 => 0}
      #   end
      # end

      # def previous_header_num

      # end

  end

  # def list(contents, list_type)
  #   case list_type
  #      when :ordered
  #        "<div class='h2item  h3bracket bullets'><br><br><p>\n\n.nr step 0 1\n#{contents}\n</p></div>\n<br><br>"
  #      when :unordered
  #        "<div class='h2item h3bracket'><br><br><p>\n\n#{contents}</p></div>\n<br><br>"
  #      end
  # end

  def list_item(text, list_type)
    case list_type
       when :ordered
         "<div class='h2item  h3bracket bullets'><p>\n\n.nr step 0 1\n#{contents}\n</p></div>\n"
       when :unordered
         "<div class='h2item h3bracket'><p>\n\n<span class='bulletmark'>●</span>#{text}</p></div>\n"
       end
  end

  
  def image(link, title, alt_text)
  # "<img src='http://#{title}.jpg.to'>"
    if link == nil
      "<p><img src='http://#{alt_text}.jpg.to' style='width:90%;'></p>"
    else
    "<p><img src='#{link}' alt='#{alt_text}' style='width: 90%;'/></p>"
    end
  end



  def double_emphasis(text)
    "<strong style='background-color: #FFFA55;'>#{text}</strong>"
  end


end

app/models/text_map.rb
# == Schema Information
#
# Table name: text_maps
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  text       :string(255)
#


require 'redcarpet'

class TextMap < ActiveRecord::Base



	def format_text

		renderer = MyHTMLRenderer.new(render_options = {})
		markdown = Redcarpet::Markdown.new(renderer, extensions = {})

		base_string = self.text
		 
		rendered_string = markdown.render base_string

		return rendered_string

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/text_maps_controller.rb
class TextMapsController < ApplicationController
  before_action :set_text_map, only: [:show, :edit, :update, :destroy]

  # GET /text_maps
  # GET /text_maps.json
  def index
    @text_maps = TextMap.all
    @text_map = TextMap.new
  end

  # GET /text_maps/1
  # GET /text_maps/1.json
  def show
    @text_map = TextMap.find(params[:id])
  end

  # GET /text_maps/new
  def new
    @text_map = TextMap.new
  end

  # GET /text_maps/1/edit
  def edit
    @text_map = TextMap.find(params[:id])
  end

  # POST /text_maps
  # POST /text_maps.json
  def create
    @text_map = TextMap.new(text_map_params)

    respond_to do |format|
      if @text_map.save
        format.html { redirect_to @text_map, notice: 'Text map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @text_map }
      else
        format.html { render action: 'new' }
        format.json { render json: @text_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_maps/1
  # PATCH/PUT /text_maps/1.json
  def update
    respond_to do |format|
      if @text_map.update(text_map_params)
        format.html { redirect_to @text_map, notice: 'Text map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @text_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_maps/1
  # DELETE /text_maps/1.json
  def destroy
    @text_map.destroy
    respond_to do |format|
      format.html { redirect_to text_maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_map
      @text_map = TextMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_map_params
      params.require(:text_map).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_maps_helper.rb
module TextMapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <title>Bullet Palatte</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/text_maps/_form.html.erb
<%= form_for @text_map do |f| %>
    <%= f.text_area :text, :class=>"text-area"%><br><br>
    <%= f.submit "Update", :class => "submitButton" %>
  <% end %>

app/views/text_maps/edit.html.erb
<h1>Editing text_map</h1>

<%= render 'form' %>


<br><br><br>
<h3>
	<%= link_to 'Show', @text_map%> |
	<%= link_to 'Back', text_maps_path %>
</h3>

app/views/text_maps/index.html.erb
<body>

  <h1 id="welcome">Bullet Palette <i class="fa fa-flag-checkered"></i></h1>
  <%= form_for @text_map do |f| %>
    <%= f.text_area :text, :class=>"text-area", :value => '# Bullet Palette

## turns your bullets into a beautiful visual poster
### a list of bullets looks really boring
### turn them into art with a click
### ![visualnotes]()
### ![colorfulnotetaking]()

## Bullet Palette runs on markdown. Which means:
- One # for a title
- Two ## for an indent
- Three ### for more indent
- **Highlight text with two asterisks around it**
- Bullet lists with -, *, or •
- \!\[apple\]\(\) will output a picture of an ![apple]()
- \[Link to Markdown\]\(http://daringfireball.net/projects/markdown\) will output a [Link to Markdown](http://daringfireball.net/projects/markdown)'%><br><br>
    <%= f.submit "Posterize", :class => "submitButton"%>
  <% end %>
</body>


<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @text_maps.each do |text_map| %>
      <tr>
        <td><%= link_to 'Show', text_map %></td>
        <td><%= link_to 'Edit', edit_text_map_path(text_map) %></td>
        <td><%= link_to 'Destroy', text_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/text_maps/new.html.erb
<h1>New text_map</h1>

<%= render 'form' %>

<%= link_to 'Back', text_maps_path %>

app/views/text_maps/show.html.erb
<script>

$(document).ready(function(){
	$('.container').masonry({
		containerStyle: 'absolute',
  	itemSelector: '.h1bracket'
  });

	$('.h1bracket').masonry({
		//columnWidth: 200,
		containerStyle: 'absolute',
  	itemSelector: '.h2bracket',
  	"stamp": ".h1box"
  });

  $('.h2bracket').masonry({
  	//columnWidth: 300,
		containerStyle: 'absolute',
  	itemSelector: '.h3bracket',
  	"stamp": ".h2box"
  });
});

</script>

<%= javascript_include_tag "masonry.pkgd.min.js" %>

<div class="container">
<%= @text_map.format_text.html_safe %><br>
</div>
</div>
</div>

<div id="footer">
	<p> Bullet Palette generates your notes into a beautiful online poster. Make <%= link_to 'New', root_path %> or Edit <%= link_to "this one", edit_text_map_path %>.</p>
</div>

<script>
  $(function(){
    $('#container').masonry({
      itemSelector: '.box',
      columnWidth: 200 //一列の幅サイズを指定
    });
  });
</script>